### ISSUE TITLE
Crashes when loaded on Server

### ISSUE THREAD

**Issue by NielsPilgaard** [CJMinecraft01/ReloadAudioDriverForge#3]
Hello o/

If RAD is in the mods folder of a server, it prevents it from starting:
https://gist.github.com/NillerMedDild/1caa8a137a618525aba7ce559b5ff3aa

**Comment by Dogatron03** [comment]
Yep its a clientside only mod.

**Comment by NielsPilgaard** [comment]
It would be nice if you could fix the crash, so servers don't appear incompatible because of modlist differences.

**Comment by Dogatron03** [comment]
Okay, yes that shouldn't happen, it's a simple fix in the @Mod annotation
and either myself or CJ will fix tomorrow.

**Comment by CJMinecraft01** [comment]
Should be fixed in the latest version :)

**Comment by NielsPilgaard** [comment]
Thanks :) will it still crash on servers?

**Comment by CJMinecraft01** [comment]
Shouldn't any more in 1.16

**Comment by NielsPilgaard** [comment]
Double thanks!
