### ISSUE TITLE
[Forge 1.16.5] Incompatible FML modded server

### ISSUE THREAD

**Issue by F0x06** [CJMinecraft01/ReloadAudioDriverForge#5]
Hi,

the mod is not flagges as a client-only mod, resulting mod list checking when connecting to a server, 

![image](https://user-images.githubusercontent.com/7167311/110225628-af635580-7ee7-11eb-9dbb-61668f88347b.png)

Can be fixed like that on the mod constructor
```java
import net.minecraftforge.fml.ExtensionPoint;
import net.minecraftforge.fml.ModLoadingContext;
import net.minecraftforge.fml.network.FMLNetworkConstants;
import org.apache.commons.lang3.tuple.Pair;

@Mod(ReloadAudioDriver.MODID)
@Mod.EventBusSubscriber
public class ReloadAudioDriver {
    ...

    public ReloadAudioDriver()
        ModLoadingContext.get().registerExtensionPoint(ExtensionPoint.DISPLAYTEST, () -> Pair.of(() -> FMLNetworkConstants.IGNORESERVERONLY, (remote, isServer) -> true));
    }
}
````

Thanks.

**Comment by CJMinecraft01** [comment]
Thanks for reporting this and apologies for the delay in responding and fixing. This has now been applied and should hopefully fix your issue!
